"""host runtime context

Revision ID: e451e20b58e2
Revises: 630af2701d55
Create Date: 2026-09-01 20:02:41.572342
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e451e20b58e2'
down_revision: Union[str, None] = '630af2701d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kernel_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reboot_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_column('reboot_required')
        batch_op.drop_column('kernel_version')

    # ### end Alembic commands ###
