"""baseline schema

Revision ID: b4c20174d4db
Revises: 
Create Date: 2026-09-01 19:28:32.758013
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4c20174d4db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('LINUX', 'WINDOWS', name='platform'), nullable=False),
    sa.Column('last_scan_status', sa.Enum('SUCCESS', 'CONNECTION_FAILURE', 'AUTH_FAILURE', name='scan_status'), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING_SYNC', name='sync_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('package_identifier', sa.String(), nullable=True),
    sa.Column('path_expression', sa.String(), nullable=True),
    sa.Column('parent_path_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING_SYNC', name='sync_status'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['target_machines.id'], ),
    sa.ForeignKeyConstraint(['parent_path_id'], ['dependency_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('os_name', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING_SYNC', name='sync_status'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['target_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'REMEDIATED', 'ACCEPTED_RISK', name='remediation_status'), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING_SYNC', name='sync_status'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['target_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cve_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severity'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('package_identifier', sa.String(), nullable=True),
    sa.Column('dependency_path_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING_SYNC', name='sync_status'), nullable=False),
    sa.ForeignKeyConstraint(['dependency_path_id'], ['dependency_paths.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['target_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('dependencies', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    op.drop_table('cve_findings')
    op.drop_table('remediation_records')
    op.drop_table('inventories')
    op.drop_table('dependency_paths')
    op.drop_table('target_machines')
    # ### end Alembic commands ###
